"""rename department

Revision ID: 76baec463595
Revises: 2d22c56ee352
Create Date: 2024-10-01 12:13:13.940837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76baec463595'
down_revision = '2d22c56ee352'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'departments' not in inspector.get_table_names():
        op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
